# Introduction, key concepts, and course mechanics

The first class will start by providing some background on the themes we will 
be covering and getting to know each other. Please read some of Kindleberger to familiarize yourself with some background for financial crises which will be useful throughout the course. The Michie and Mollan piece will help with some broad perspective on how the City changed from the 19th to the 20th centuries. We will not discuss these in class, but they are a good place to start.

## General readings

+ [@kindlebergerManiasPanicsCrashes1996] Chapter 2 on the anatomy of financial crises [link](https://ebookcentral.proquest.com/lib/kcl/reader.action?docID=5180973&ppg=47). Kindleberger is a prolific and influential economic historian. He is most famous for this account of bubbles, as well as his interpretation of the global great depression of the interwar period.
+ [@mollanCityLondonInternational2012] [link](https://www.cambridge.org/core/services/aop-cambridge-core/content/view/9949AB1236E658813B89877F9B0E85AA/S1467222700010867a.pdf/city_of_london_as_an_international_commercial_and_financial_center_since_1900.pdf)