# The London Stock Exchange in the 19th century

This week is our opportunity to discuss the material we have covered on the LSE. We will read three articles from different traditions (history of science and technology, economic history, economics) on the LSE which I hope will offer up some different ways to think about how you might research it. We will also be looking at the testimony given in a Royal Commission into the LSE that offers some scope for understanding how brokers and dealers thought about their work (or anyway, what they would admit to thinking about it in front of an inquiry!).

## General readings

+ [@handelMaterialPoliticsFinance2021] on financial infrastructure [link](https://www.cambridge.org/core/journals/enterprise-and-society/article/material-politics-of-finance-the-ticker-tape-and-the-london-stock-exchange-1860s1890s/7BA79594BE371FBD270D7C0D701F2B33)
+ [@chavazHighDryLiquidity2017] on exchange structure and liquidity [link](https://www.cambridge.org/core/journals/journal-of-economic-history/article/high-dry-the-liquidity-and-credit-of-colonial-and-foreign-government-debt-and-the-london-stock-exchange-18801910/2401635333AE75C533774C57CFD77226)
+ [@fjesmeRejectedStockExchange2020] on LSE admission and screening [link](https://www.sciencedirect.com/science/article/pii/S0304405X20302336)


## Primary sources

We will be looking at excerpts from the Royal Commission on the London Stock Exchange which I will provide.

+ [@RoyalComOrigin1878]

## Additional readings

+ [@nealEvolutionStructurePerformance2006a] [link](https://www.jstor.org/stable/41378447)
+ [@michieLondonStockExchange2001]




