---
title: "Syllabus"
subtitle: "London, City of Capital, 1825-2008"
author: "Dr. Gabriel Geisler Mesevage"
date: "`r Sys.Date()`"
documentclass: book
output_dir: "docs"
output:
  bookdown::gitbook: default
bibliography: capital.bib
link-citations: no
csl: history_and_theory.csl
linkcolor: blue
urlcolor: blue
---

```{r start, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(bookdown)
```

# Introduction: London, City of Capital, 1825-2008 {-}

London has functioned as a financial hub for over two centuries. It was through London that British and international savings were funneled into Latin American sovereign debt, British railroads, Southern African diamond mines, or North American mortgages. The nineteenth century saw London grow to become the premiere international investment market, and witnessed the growth of central banking doctrine at the Bank of England, the growth of the London Stock Exchange, and the establishment of supporting institutions such as a financial press. During the financial turbulence of the inter-war years London sat at the centre of efforts to maintain the gold standard, and in the aftermath of World War II it was London where the international market for dollars grew. Sterling instability in the 20th century was funneled through the London capital market, and the financial deregulation of the last quarter of the twentieth century witnessed further growth of the City. This module aims to analyze the role of London as an international financial hub, focusing in particular on the role of crises in driving institutional and regulatory change. We open with the Panic of 1825 -- which led to bank failures stemming from overseas lending to Latin America -- and close with the Global Financial Crisis. The module will be structured around relevant primary sources, which we will link to ideas from the broader historiography. The focus of the module is the economic and financial history of London as a capital market. 


## About Group III Modules

Group III modules are distinctive in that they are focused on a large body of primary source material (approximately 1,000 pages). Students develop a close familiarity with these ‘specified primary sources’ and prepare to be examined on their knowledge and understanding of this body of material at the end of the year. Group IIIs constitute the largest component of the BA, at 60 credits. Each Group III technically comprises two separate modules of 30 credits each: one leading to an end-of-year examination, and the other leading to a dissertation.

# Background Reading & Sources {-}

## Financial History Overviews

+ Barry Eichengreen, Globalizing Capital: A History of the International Monetary System, 3rd Edition, Princeton University Press: 2019. (Or any edition).
+ Charles P. Kindleberger, Manias, Panics and Crashes: A History of Financial Crises, 3rd Edition, Wiley: 1996. (Or any edition).
+ Youssef Cassis, Capitals of Capital: A History of International Financial Centres, 1780-2005, Cambridge University Press: 2012.

## General economics

+ Robert Allen, *Global Economic History: a very short introduction*, OUP: 2011. Allen is a prolific economic historian whose work we will encounter throughout the course, and this is a remarkably concise introduction to a very large topic.
+ [Partha Dasgupta, *Economics: a very short introduction*, OUP: 2007.](https://ebookcentral.proquest.com/lib/kcl/reader.action?docID=415258&ppg=2) This is a very well-reviewed brief introduction.
+ [Steven Durlauf & Lawrence Blume, *The New Palgrave Dictionary of Economics*.](https://link.springer.com/referencework/10.1057/978-1-349-95121-5#editorsandaffiliations) A helpful reference for looking up economic ideas you are unfamiliar with.

## Data sources

+ [Federal Reserve Economic Data (FRED)](https://fred.stlouisfed.org/) contains an enormous number of series. Most data is contemporary but they have some series that are historical.
+ [Jordà-Schularick-Taylor Macrohistory Database](http://www.macrohistory.net/data/) is developed by economic historians and contains macroeconomic data.
+ [http://eh.net/](http://eh.net/) is run by the Economic History Association and posts a number of published data series on its website. It also maintains [MeasuringWorth](https://www.measuringworth.com/datasets.html) for historical value comparisons.
+ [The Investor's Monthly Manual and digitized data 1869-1929 at Yale International Centre for Finance](https://som.yale.edu/faculty-research/our-centers-initiatives/international-center-finance/data/historical-financial-research-data/london-stock-exchange)
+ [The Economist Historical Archive, 1843-2014](https://go.gale.com/ps/start.do?p=ECON&u=kings)
+ [Financial Times Historical Archive, 1888-2010](https://go.gale.com/ps/start.do?p=FTHA&u=kings)
+ [The Times Digital Archive, 1785-2014, market coverage picks up around the 1840s](https://go.gale.com/ps/start.do?p=TTDA&u=kings)
+ [British Library Newspapers](https://go.gale.com/ps/start.do?p=BNCN&u=kings)

## Archives in London

+ [Guildhall Library Business History Sources](https://www.cityoflondon.gov.uk/things-to-do/guildhall-library/collections/Pages/Business-history.aspx)
+ [London Metropolitan Archives](https://www.cityoflondon.gov.uk/things-to-do/london-metropolitan-archives/the-collections/Pages/default.aspx)
+ [The National Archives](https://nationalarchives.gov.uk/)

# Assessment {-}

## Summative Assessment

### Examination

+ The exam is worth 30 credits. It will be **online**. It will probably last 24 hours although more details will be provided closer to the exam date.
+ Format: you must EITHER answer two gobbet questions and one essay question, OR one gobbet question and two essay questions.
+ The exam paper will contain two gobbet questions and eight essay questions.
+ Gobbet questions: each gobbet question reproduces seven gobbets (extracts) from primary sources and says: ‘Comment upon THREE gobbets from the following.’ For each question, you give three SEPARATE comments: one for each gobbet.
+ Essay questions: these are similar in form to essay questions on other types of module, but you are encouraged to draw on your knowledge of primary sources, as well as relevant secondary literature, in your answers.

### Dissertation 

+ 10,000 words in length; submitted early on in Exam Term.
+ Students devise a dissertation topic and title, taking guidance from me.
+ The dissertation must make use of primary source material: this may
include the primary sources covered in class, but students will often make use of
other primary source material which they have identified.
+ Each student is entitled to up to four half-hour meetings with me to discuss their
dissertation.
+ Each student can submit to me a maximum of 3,000 words in draft form for feedback in a
meeting (as part of the allowance of four half-hour meetings).
+ Our session in week 6 (after reading week) in the first semester is reserved as DISSERTATION WORKSHOP #1: students will give short presentations outlining their ideas for dissertation topics and discussing the primary sources and secondary works that will be used (details below).
+ Our session in week 11 (after Christmas) in the second semester is reserved as DISSERTATION WORKSHOP #2: students will present their progress and discuss how they have used primary sources as evidence (details below).

## Formative work

+ Each student will be responsible for introducing the primary sources 4 times (twice each semester)
    - Given student numbers, this will be done in teams
    - 'Presentation' slots for semester 1 will be picked in the first session
+ Each student will write 4 gobbets (500 words) and 2 essays (1,500 words) as practice.
+ I will grade these assignments provided that they are submitted on time.
+ The essays are due by the end of Semester 1 and 2 respectively.
    - You can simply email the work to me
    - You can write the essays sooner if you like
    - I need to get your last essays at least 3 weeks before the exam if you want my feedback in time.
    
### Notes on presentations

+ These are not formal presentations, you are simply expected to initiate the discussion of the sources by talking about them for ~5 minutes. 
+ There will be 2-3 presenters each week: you will need to work together to coordinate your discussion
    - Each presenter should speak for ~5 minutes.
+ If you want to make slides/use pictures/other media feel free
+ Focus on the writers biases and motivations
+ Focus on the relationship between the sources and the ideas in the secondary material
+ Focus on what kind of interesting questions the sources raise for further discussion

## How to write a gobbet

A gobbet is a short commentary on an excerpt from a primary source. You should typically write 2 paragraphs (about 500-700 words).

In your first paragraph, you should draw out basic information about the source such as *who* is the author, *what* are they commenting on and *why*. You may also need to state *when* and draw out which particular event or events the source is reacting to.

Your second paragraph is a chance to show off your creativity: how does the source relate to some of the broader intellectual themes discussed in secondary sources? What is the *significance* of the source? What does it reveals that is *of interest to scholars* and why is it interesting to them? Did the source itself have consequences when read by others? Do we know, from other sources, that the author's views later changed? Does the identity of the author, or the timing of the source's writing,
give it a particular value to the historian? You can also use this paragraph for some more sophisticated analyses of potential source biases, and for the contextualization of the source's claims.

In grading a gobbet, your work in the first paragraph is necessary but not sufficient for a good grade: if you wrote a perfect first paragraph and an atrocious (or non-existent) second paragraph I would grade you between 55-60.
