---
title: "Syllabus"
subtitle: "London, City of Capital, 1825-2008"
author: "Dr. Gabriel Geisler Mesevage"
date: "`r Sys.Date()`"
documentclass: book
output_dir: "docs"
output:
  bookdown::gitbook: default
bibliography: capital.bib
link-citations: no
csl: history_and_theory.csl
linkcolor: blue
urlcolor: blue
---

```{r start, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(bookdown)
```

# Introduction: London, City of Capital, 1825-2008 {-}

London has functioned as a financial hub for over two centuries. It was through London that British and international savings were funneled into Latin American sovereign debt, British railroads, Southern African diamond mines, or North American mortgages. The nineteenth century saw London grow to become the premiere international investment market, and witnessed the growth of central banking doctrine at the Bank of England, the growth of the London Stock Exchange, and the establishment of supporting institutions such as a financial press. During the financial turbulence of the inter-war years London sat at the centre of efforts to maintain the gold standard, and in the aftermath of World War II it was London where the international market for dollars grew. Sterling instability in the 20th century was funneled through the London capital market, and the financial deregulation of the last quarter of the twentieth century witnessed further growth of the City. This module aims to analyze the role of London as an international financial hub, focusing in particular on the role of crises in driving institutional and regulatory change. We open with the Panic of 1825 -- which led to bank failures stemming from overseas lending to Latin America -- and close with the Global Financial Crisis. The module will be structured around relevant primary sources, which we will link to ideas from the broader historiography. The focus of the module is the economic and financial history of London as a capital market. 


## About Group III Modules

Group III modules are distinctive in that they are focused on a large body of primary source material (approximately 1,000 pages). Students develop a close familiarity with these ‘specified primary sources’ and prepare to be examined on their knowledge and understanding of this body of material at the end of the year. Group IIIs constitute the largest component of the BA, at 60 credits. Each Group III technically comprises two separate modules of 30 credits each: one leading to an end-of-year examination, and the other leading to a dissertation.

# Background Reading & Sources {-}

## Financial History Overviews

+ Barry Eichengreen, Globalizing Capital: A History of the International Monetary System, 3rd Edition, Princeton University Press: 2019. (Or any edition).
+ Charles P. Kindleberger, Manias, Panics and Crashes: A History of Financial Crises, 3rd Edition, Wiley: 1996. (Or any edition).
+ Youssef Cassis, Capitals of Capital: A History of International Financial Centres, 1780-2005, Cambridge University Press: 2012.

## General economics

+ Robert Allen, *Global Economic History: a very short introduction*, OUP: 2011. Allen is a prolific economic historian whose work we will encounter throughout the course, and this is a remarkably concise introduction to a very large topic.
+ [Partha Dasgupta, *Economics: a very short introduction*, OUP: 2007.](https://ebookcentral.proquest.com/lib/kcl/reader.action?docID=415258&ppg=2) This is a very well-reviewed brief introduction.
+ [Steven Durlauf & Lawrence Blume, *The New Palgrave Dictionary of Economics*.](https://link.springer.com/referencework/10.1057/978-1-349-95121-5#editorsandaffiliations) A helpful reference for looking up economic ideas you are unfamiliar with.

## London as a financial center

+ [@cassisCapitalsCapitalHistory2006]  [link](https://ebookcentral.proquest.com/lib/kcl/reader.action?docID=802981&ppg=90) is a classic on international financial centers
+ David Kynaston, *The City of London*, in 4 volumes is an accessible popular history

## Data sources

+ [Federal Reserve Economic Data (FRED)](https://fred.stlouisfed.org/) contains an enormous number of series. Most data is contemporary but they have some series that are historical.
+ [Jordà-Schularick-Taylor Macrohistory Database](http://www.macrohistory.net/data/) is developed by economic historians and contains macroeconomic data.
+ [http://eh.net/](http://eh.net/) is run by the Economic History Association and posts a number of published data series on its website. It also maintains [MeasuringWorth](https://www.measuringworth.com/datasets.html) for historical value comparisons.
+ [The Investor's Monthly Manual and digitized data 1869-1929 at Yale International Centre for Finance](https://som.yale.edu/faculty-research/our-centers-initiatives/international-center-finance/data/historical-financial-research-data/london-stock-exchange)
+ [The Economist Historical Archive, 1843-2014](https://go.gale.com/ps/start.do?p=ECON&u=kings)
+ [Financial Times Historical Archive, 1888-2010](https://go.gale.com/ps/start.do?p=FTHA&u=kings)
+ [The Times Digital Archive, 1785-2014, market coverage picks up around the 1840s](https://go.gale.com/ps/start.do?p=TTDA&u=kings)
+ [British Library Newspapers](https://go.gale.com/ps/start.do?p=BNCN&u=kings)

## Archives in London

+ [Guildhall Library Business History Sources](https://www.cityoflondon.gov.uk/things-to-do/guildhall-library/collections/Pages/Business-history.aspx)
+ [London Metropolitan Archives](https://www.cityoflondon.gov.uk/things-to-do/london-metropolitan-archives/the-collections/Pages/default.aspx)
+ [The National Archives](https://nationalarchives.gov.uk/)
+ [Bank of England Archives](https://www.bankofengland.co.uk/archive)
+ [Baring Archive](https://baringarchive.org.uk/)

# Assessment {-}

## Summative Assessment

### Examination

+ The exam is worth 30 credits. 
+ Format: you must EITHER answer two gobbet questions and one essay question, OR one gobbet question and two essay questions.
+ The exam paper will contain two gobbet questions and eight essay questions.
+ Gobbet questions: each gobbet question reproduces seven gobbets (extracts) from primary sources and says: ‘Comment upon THREE gobbets from the following.’ For each question, you give three SEPARATE comments: one for each gobbet.
+ Essay questions: these are similar in form to essay questions on other types of module, but you are encouraged to draw on your knowledge of primary sources, as well as relevant secondary literature, in your answers.

### Dissertation 

+ 10,000 words in length; submitted early on in Exam Term.
+ Students devise a dissertation topic and title, taking guidance from me.
+ The dissertation must make use of primary source material: this may
include the primary sources covered in class, but students will often make use of other primary source material which they have identified.
+ Each student is entitled to up to four half-hour meetings with me to discuss their dissertation.
+ Each student can submit to me a maximum of 3,000 words in draft form for feedback in a meeting (as part of the allowance of four half-hour meetings).
+ Our session in week 6 (after reading week) in the first semester is reserved as DISSERTATION WORKSHOP #1: students will give short presentations outlining their ideas for dissertation topics and discussing the primary sources and secondary works that will be used (details below).
+ Our session in week 11 (after Christmas) in the second semester is reserved as DISSERTATION WORKSHOP #2: students will present their progress and discuss how they have used primary sources as evidence (details below).

## Formative work

+ Each student will be responsible for introducing the primary sources several times during the year -- exactly how often depends on class size.
+ Each student will write 4 gobbets (500 words) and 2 essays (1,500 words) as practice.
+ I will grade these assignments provided that they are submitted on time.
+ The essays are due by the end of Semester 1 and 2 respectively.
    - You can simply email the work to me
    - You can write the essays sooner if you like
    - I need to get your last essays at least 3 weeks before the exam if you want my feedback in time.

# How to write a gobbet

A gobbet is a short commentary on an excerpt from a primary source. You should typically write 2 paragraphs (about 500-700 words).

In your first paragraph, you should draw out basic information about the source such as *who* is the author, *what* are they commenting on and *why*. You may also need to state *when* and draw out which particular event or events the source is reacting to.

Your second paragraph is a chance to show off your creativity: how does the source relate to some of the broader intellectual themes discussed in secondary sources? What is the *significance* of the source? What does it reveals that is *of interest to scholars* and why is it interesting to them? Did the source itself have consequences when read by others? Do we know, from other sources, that the author's views later changed? Does the identity of the author, or the timing of the source's writing,
give it a particular value to the historian? You can also use this paragraph for some more sophisticated analyses of potential source biases, and for the contextualization of the source's claims.

In grading a gobbet, your work in the first paragraph is necessary but not sufficient for a good grade: if you wrote a perfect first paragraph and an atrocious (or non-existent) second paragraph I would grade you between 55-60.

<!--chapter:end:index.Rmd-->

# Introduction, key concepts, and course mechanics

The first class will start by providing some background on the themes we will 
be covering and getting to know each other. Please read some of Kindleberger to familiarize yourself with some background for financial crises which will be useful throughout the course. The Michie and Mollan piece will help with some broad perspective on how the City changed from the 19th to the 20th centuries. We will not discuss these in class, but they are a good place to start.

## General readings

+ [@kindlebergerManiasPanicsCrashes1996] Chapter 2 on the anatomy of financial crises [link](https://ebookcentral.proquest.com/lib/kcl/reader.action?docID=5180973&ppg=47). Kindleberger is a prolific and influential economic historian. He is most famous for this account of bubbles, as well as his interpretation of the global great depression of the interwar period.
+ [@mollanCityLondonInternational2012] [link](https://www.cambridge.org/core/services/aop-cambridge-core/content/view/9949AB1236E658813B89877F9B0E85AA/S1467222700010867a.pdf/city_of_london_as_an_international_commercial_and_financial_center_since_1900.pdf)

<!--chapter:end:01-week.Rmd-->

# Lending money abroad: the global sovereign debt crisis of 1825

We will start with what is often viewed as the first international sovereign debt crisis centered on London. We will try to get a sense for the nature of the 1825 crisis and its causes, and then think through the primary sources in terms of what they tell us about the information environment for speculators in the early 19th century.

## General Readings

+ [@jenksMigrationBritishCapital1927] [link](https://ia801604.us.archive.org/29/items/in.ernet.dli.2015.224193/2015.224193.The-Migration_text.pdf) Chapter 2.^[Jenk's book is an interesting financial history up to 1875 written in the 1920's before the Great Depression.]
+ [@clavel_2020] [link](https://doi.org/10.1017/eso.2020.25)^[This is a recent reinterpretation of the Poyais scheme.]

## Primary Sources

+ [@disraeliInquiryPlansProgress1825] [link](http://hdl.handle.net/2027/mdp.39015063950995) read up to page 21 and then skim a section on one country of your choice.^[Disraeli was involved in speculation in South America with an investor named J. D. Powles who also commissioned him to write this promotional pamphlet.]
+ [@WaysMeansEvery1824] [link](https://link.gale.com/apps/doc/U0104561666/MOME?u=ull_ttda&sid=MOME&xid=045a6e68) this is an example of a pamphlet written for investors in the 1820s.

## Additional reading

+ [@tookeHistoryPricesVol1838] [link](http://archive.org/details/in.ernet.dli.2015.42727) read pp. 148 to 171.
+ [@nealFinancialCrisis18251998] [link](https://research.stlouisfed.org/publications/review/1998/05/01/the-financial-crisis-of-1825-and-the-restructuring-of-the-british-financial-system/)
+ [@pettisVolatilityMachineEmerging2001] [link](https://ebookcentral.proquest.com/lib/kcl/reader.action?docID=431191&ppg=72) Chapter 4
+ [@marichalsalinasCenturyDebtCrises1989] Ch. 1 & 2


<!--chapter:end:02-week.Rmd-->

# The London Stock Exchange Archive Visit

We will be visiting Guildhall library for a visit to the London Stock Exchange archive as well as other useful and important resources for business and economic historians. Our visit will take place at 10:30 am at Guildhall Library. Please arrive early.

In preparation for the visit it would be good to read Morgan & Thomas for background and I would also like you to look at the rules and regulations of the exchange in 1847 which will help you to understand the structure of the exchange *and* the structure of the archive we will be visiting.

To see where the LSE fits in more broadly read Taylor's article on LSE vs outside brokers and look at the polemic against the LSE brokers written by Mortimer.

+ [@morganStockExchangeIts1969] read Chapter 4 "The Development of an Organized Market"
+ [@taylorOutsideLondonStock2020] [link](https://www.cambridge.org/core/product/identifier/S1467222720000233/type/journal_article) on outside brokers vs LSE brokers

## Primary sources

+ [@RegulationsAdoptedCommittee1847] [link](https://books.googleusercontent.com/books/content?req=AKW5QacIwGHn20rqReIgbN_oGOc_Bt_fW8pdyKxlC09bYAwX3XOssxwTJthFknFUu177BshL5JA8J1ucpjgn-uh2dXpeFeh-fqGdtWZ5D2ixh8Chcrd2wMpyEvEu_l-q5MOwUlpf6GpNjNTpNqwchxfjJ5obkjQCB7thIA9SKnNwpipN0vbYcNRrLG2SClz9MGFKNqf6Z-mqLcRgmOqsko4l53FEfrySnoAnBje8jRT1IqCHzSPXo3juEpnzfEoqiD48Im02BSBkdFqLIDlDiYoXmyDe_RHbOK8c2nBL7rSykitTvXA6mvk)
+ [@mortimerEveryManHis1807] [link](https://link.gale.com/apps/doc/U0103061473/MOME?u=ull_ttda&sid=MOME&xid=162e645a) read the Preface and Chapter III.

<!--chapter:end:03-week.Rmd-->

# The London Stock Exchange in the 19th century

This week is our opportunity to discuss the material we have covered on the LSE. We will read three articles from different traditions (history of science and technology, economic history, economics) on the LSE which I hope will offer up some different ways to think about how you might research it. We will also be looking at the testimony given in a Royal Commission into the LSE that offers some scope for understanding how brokers and dealers thought about their work (or anyway, what they would admit to thinking about it in front of an inquiry!).

## General readings

+ [@handelMaterialPoliticsFinance2021] on financial infrastructure [link](https://www.cambridge.org/core/journals/enterprise-and-society/article/material-politics-of-finance-the-ticker-tape-and-the-london-stock-exchange-1860s1890s/7BA79594BE371FBD270D7C0D701F2B33)
+ [@chavazHighDryLiquidity2017] on exchange structure and liquidity [link](https://www.cambridge.org/core/journals/journal-of-economic-history/article/high-dry-the-liquidity-and-credit-of-colonial-and-foreign-government-debt-and-the-london-stock-exchange-18801910/2401635333AE75C533774C57CFD77226)
+ [@fjesmeRejectedStockExchange2020] on LSE admission and screening [link](https://www.sciencedirect.com/science/article/pii/S0304405X20302336)


## Primary sources

We will be looking at excerpts from the Royal Commission on the London Stock Exchange which I will provide.

+ [@RoyalComOrigin1878]

## Additional readings

+ [@nealEvolutionStructurePerformance2006a] [link](https://www.jstor.org/stable/41378447)
+ [@michieLondonStockExchange2001]





<!--chapter:end:04-week.Rmd-->

# The railway mania of 1845 and crisis of 1847

The railway mania is possibly the first major tech-stock bubble -- certainly the most spectacular one at least until the dotcom bubble of the 1990s. We will try to get a sense for the mania, and then look in more detail at the process of company promotion.

## General readings

+ [@campbellGovernmentPolicyBritish2014] [link](https://oxford.universitypressscholarship.com/view/10.1093/acprof:oso/9780199688661.001.0001/acprof-9780199688661-chapter-4)
+ [@odlyzkoCollapseRailwayMania2011] [link](http://www.tandfonline.com/doi/abs/10.1080/21552851.2011.605556)

## Primary sources

+ [@aytounHowWeGot1845] [link](http://www.dtc.umn.edu/~odlyzko/rrsources/glen6.pdf)^[The text is reproduced on Andrew Odlyzko's website. He has supplied a helpful introduction which you should also read.]
+ [@anon.ShortSureGuide1847] [link](https://link.gale.com/apps/doc/U0106715654/MOME?u=ull_ttda&sid=MOME&xid=f232123e)

<!--chapter:end:05-week.Rmd-->

# Dissertation Chat 1

Each person in class will get a chance to talk for a few minutes about their dissertation project and what they are planning. 

<!--chapter:end:06-week.Rmd-->

# Baring Archive Class Trip

We will be taking a class trip to the Baring Archive in the city for an introduction to some of the material held on a leading financial institution once described as the 'sixth great power'.

Our tour will start at 10:30 am. Please arrive at 10:15 at 8-10 Moorgate London EC2R 6DA.

## Background reading

+ [@chapmanRiseMerchantBanking2006] Chapters 2 and 4 [link](https://ebookcentral.proquest.com/lib/kcl/reader.action?docID=1144445&ppg=31)

<!--chapter:end:07-week.Rmd-->

# Foreign Lending and The Baring Crisis

## General readings

+ [@floresInformationAsymmetriesConflict2011] [link](https://www.cambridge.org/core/article/information-asymmetries-and-conflict-of-interest-during-the-baring-crisis-188018901/F7A751A4AC3D90669DFD370A387D3E9C)
+ [@dellapaoleraMonetaryFinancialWreck2001] [link](https://www.nber.org/chapters/c8837.pdf)


## Primary sources

We will be looking at the Barings Archive for sources on the
Argentine crisis of 1890. In addition to the below, you will go
to the [online holdings of the Barings Archive](https://baring.access.preservica.com/archive/) and select
2 documents of your choice. This will likely involve a lot of
searching. There is correspondance in French (Barings to Argentine
Government), Spanish (Argentine Government to Barings), and 
German (consortium banks to Barings) in addition to English 
so feel free to make use of any special language skills if you
like.

+ [@CorrespondenceDiscontoGesellschaft] [link](https://baring.access.preservica.com/uncategorized/IO_b436c123-97cd-42f2-a3c7-aed0cdbbffec/?view=gallery)
+ [@SchemeConversionArgentine1888] [link](https://baring.access.preservica.com/uncategorized/IO_baeb649b-dbe3-46c5-9d0c-afb75887c7a2/)
+ [@ProposalArgentineGovernment] [link](https://baring.access.preservica.com/uncategorized/IO_fabf01ef-16ac-4d52-80f6-8ed5a8add171/?view=gallery)
+ [@CorrespondenceGeorgeWhite] [link](https://baring.access.preservica.com/uncategorized/SO_4177cba6-61a1-46a7-8c10-148bf2e2d464/)
+ [@TelegramDiscontoGesellschaft1889] [link](https://baring.access.preservica.com/uncategorized/SO_77f5601d-3087-4905-8c42-194218d3cbc2/)
+ [@DraftResponseLuis1893] [link](https://baring.access.preservica.com/uncategorized/IO_dd0844b9-214a-4f86-9cd3-ffaf91ed6e25/?view=gallery)
+ [@CorrespondanceFosterBraithwaite] [link](https://baring.access.preservica.com/uncategorized/IO_7627b2eb-bbbc-44db-9eb2-1713862658af/?view=gallery)

<!--chapter:end:08-week.Rmd-->

# The London money market

## General readings

+ [@bignonBagehotBeginnersMaking2012] [link](https://doi.org/10.1111/j.1468-0289.2011.00606.x)
+ [@xuReshapingGlobalTrade2020] [link](https://chenzi-xu.com/docs/reshaping_global_trade_Xu.pdf) You can listen to the author discuss her paper [here](https://www.tradetalkspodcast.com/podcast/138-trade-and-the-worst-financial-crisis-of-the-century-in-1866/).
+ [@accominottiOriginationDistributionMoney2021] [link](https://doi.org/10.1111/ehr.13049)

## Primary sources

+ [@bagehotLombardStreetDescription1873] Chs 1 & 2. Bagehot is excellent and this is an important book and you should read as much as you can.
+ [@Panic1866] [link](https://link.gale.com/apps/doc/GP4100418639/ECON?u=kings&sid=ECON&xid=4a302558)


<!--chapter:end:09-week.Rmd-->

# Financial information in the 19th century

## General readings

+ [@porterTrustedGuideInvesting1986] [link](https://doi.org/10.1080/00076798500000068)
+ [@nyeBoomCrisisBust2015] [link](https://ebookcentral.proquest.com/lib/kcl/reader.action?docID=1775338&ppg=244)
+ [@flandreauSeparationInformationLending2014] [link](http://dx.doi.org/10.1080/03585522.2014.950602)

## Primary sources

+ [@duguidHowReadMoney1902] [link](https://ia802705.us.archive.org/4/items/howtoreadmoneyar00dugurich/howtoreadmoneyar00dugurich.pdf). This is a book on how to read financial coverage in 19th century newspapers written at the turn of the century. Read chapters XXIII, XXIV and XXV.
+ I want you to search the [Financial Times Historical Archive](https://go.gale.com/ps/i.do?p=FTHA&sw=w&u=kings&v=2.1&pg=BasicSearch&it=static&sid=FTHA) in its first decade, and find examples of material you believe was paid to be inserted.

<!--chapter:end:10-week.Rmd-->

# Dissertation chat 2

<!--chapter:end:11-week.Rmd-->

# International Finance and WWI

## General readings

+ [@robertsSavingCityGreat2014] [link](http://ebookcentral.proquest.com/lib/kcl/detail.action?docID=1538366) Chapter 1.
+ [@ExtraordinaryStoryBritain] [link](https://voxeu.org/content/extraordinary-story-britain-s-early-efforts-finance-first-world-war)

## Primary sources

+ [@keynesWarFinancialSystem1914] [link](https://doi.org/10.2307/2222023)
+ [The Bank of England 1914-21 (Unpublished War History)](https://www.bankofengland.co.uk/archive/bank-of-england-1914-21-ww1) Read Vol. 4 Chapter X.

<!--chapter:end:12-week.Rmd-->

# The reparations problem

## General readings

+ [@eichengreenGlobalizingCapitalHistory2008] Ch. 3 interwar instability [link](https://ebookcentral.proquest.com/lib/kcl/reader.action?docID=5782434&ppg=56)
+ [@ritschlReparationTransfersBorchardt1998] [link](http://www.piketty.pse.ens.fr/files/Ritschl1998.pdf)

## Primary sources

+ [@keynesEconomicConsequencesPeace2019] Read "Germany's capacity to pay", "The German Counter-Proposals", and "Remedies" [link](https://oll.libertyfund.org/title/keynes-the-economic-consequences-of-the-peace)
+ [@mantouxCarthaginianPeaceEconomic2000] Read Chapter 2 "Prophecy and Persuasion". I will put the pdf on Keats.

<!--chapter:end:13-week.Rmd-->

# The gold standard and the great depression

## General readings

+ [@bernankeGoldStandardDeflation1990] [link](http://www.nber.org/papers/w3488.pdf)
+ [@eichengreenGoldStandardGreat2000] [link](https://www.jstor.org/stable/20081742)

## Primary sources

<!-- + Norman Montagu's diaries from BoE archive? -->
+ [@stampReportMacmillanCommittee1931] [link](https://doi.org/10.2307/2223900)
+ [@macmillanReportCommitteeFinance1931] [link](https://parlipapers.proquest.com/parlipapers/docview/t70.d75.1930-031248?accountid=11862)

<!--chapter:end:14-week.Rmd-->

# Decolonization and the pound

## General readings

+ [@balachandranSterlingCrisisManaged1990] [link](http://journals.sagepub.com/doi/10.1177/001946469002700101)
    - This provides some helpful insight into the use of the colonies to manage the currency. Read it if you have time.
+ [@ogleFunkMoneyEnd2020] [link](https://doi.org/10.1093/pastj/gtaa001)
+ [@schenkDeclineSterlingManaging2013] Chapters 2 and 3 (a bit long but a lot of graphs), pdf is on Keats

## No Primary Sources this week

<!--chapter:end:15-week.Rmd-->

# The Bank of England and crises in the 1970s

## General readings

+ [@michelj.oliverDownhillDevaluationBattle2007] [link](www.jstor.org/stable/4502107)
+ [@strangeSterlingBritishPolicy1971] [link](https://doi.org/10.2307/2613930)
+ [@dowBankEnglandMemoirs2014] Chapter 1
    - This is more like a primary source. PDF on Keats.

## Primary sources

+ [@OralHistoriesCentre] [link](https://www.centreforfinancialhistory.org/oral-histories/)
    - These are a series of interviews with participants in the 'Lifeboat Operation'. There are 5 interviews and we will divide up who covers them in Week 15.


<!--chapter:end:16-week.Rmd-->

# Rise of the eurodollar market

## General readings

+ [@schenkOriginsEurodollarMarket1998] [link](http://www.sciencedirect.com/science/article/pii/S0014498398906933)
+ [@greenAngloAmericanDevelopmentEuromarkets2016] [link](https://www.cambridge.org/core/product/identifier/S0260210515000480/type/journal_article)
+ [@helleinerStatesReemergenceGlobal1994] Chapter 4 "Support for the Euromarket in the 1960s" [link](https://ebookcentral.proquest.com/lib/kcl/reader.action?docID=3425975&ppg=94)

## Primary sources

+ [@burkWitnessSeminarOrigins1992] [link](https://doi.org/10.1017/S0960777300005063)


<!--chapter:end:17-week.Rmd-->

# The Big Bang and financial deregulation

## General readings

+ [@attardMakingMarketJobbers2000] [link](https://www.cambridge.org/core/services/aop-cambridge-core/content/view/27B5A3F3C440C45D2B633E603C80C185/S0968565000000019a.pdf/making_a_market_the_jobbers_of_the_london_stock_exchange_18001986.pdf)
    - Read this as background on the broker/jobber distinction if you are having trouble remembering week 4, as well as a commentary on this week's primary source.
+ [@thompsonPyrrhicVictoryGentlemanly1997] [link](https://www.jstor.org/stable/260962)
+ [@bellringerBigBangCity2014] [link](https://www.cambridge.org/core/product/identifier/S0968565014000092/type/journal_article)
+ [@wadeFinancialRegimeChange2008] [link](https://newleftreview.org/issues/II53/articles/robert-wade-financial-regime-change)

## Primary sources

+ [@attardLondonStockExchange] [link](https://sas-space.sas.ac.uk/view/collections/lseoh.html) Pick two interviews and listen to them or read transcript


<!--chapter:end:18-week.Rmd-->

# The Great Recession: transatlantic flows and mortgage mania

## General readings

+ [@toozeCrashedHowDecade2018] ch. 1 "The Wrong Crisis" and ch. 3 "Transatlantic Finance" (If you have time the intro and Ch. 2 as well.)

## Primary sources

<!-- + Not totally sure yet -->
<!-- + Property Ladder season 6 -->
<!-- + Brookings Hamilton project vs IMF or BIS report? -->
+ [@mckayBigShort2015] [link to film for KCL students](https://kcl.kanopy.com/video/big-short)
+ [@PropertyLadderTV] [Youtube Link to S06E01 early 2007](https://www.youtube.com/watch?v=FL3TBs1yKG4)

<!--chapter:end:19-week.Rmd-->

# The Great Recession: The run on repo and the aftermath

## General readings

+ [@gortonSlappedFaceInvisible2009] [link](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=1401882)
+ [@covalEconomicsStructuredFinance2009] [link](https://pubs.aeaweb.org/doi/pdfplus/10.1257/jep.23.1.3)

## Primary sources

<!-- + Congressional testimony on CSPAN -->
<!-- + Parliamentary inquiry on banking stability -->
<!-- + Andy Haldane speach? -->
+ [@haldaneBankingState] [link](https://www.bis.org/review/r091111e.pdf) Paper by Executive Director, Financial Stability at Bank of England

<!--chapter:end:20-week.Rmd-->

# Review week: Exam Prep


<!--chapter:end:21-revision-week.Rmd-->

