---
title: "Syllabus"
subtitle: "London, City of Capital, 1825-2008"
author: "Dr. Gabriel Geisler Mesevage"
date: "`r Sys.Date()`"
output:
  rmarkdown::html_document:
        toc: true
        theme: null
        highlight: null
        mathjax: null
  tint::tintHtml: 
        toc: true
  tufte::tufte_handout:
        latex_engine: xelatex
bibliography: capital.bib
link-citations: no
csl: history_and_theory.csl
linkcolor: blue
urlcolor: blue
---

```{r setup, include=FALSE}
library(tufte)
# invalidate cache when the tufte version changes
knitr::opts_chunk$set(tidy = FALSE, 
                      echo = FALSE, results = "asis")
options(htmltools.dir.version = FALSE)
```

# Semester 1

## 1. Introduction, key concepts, and course mechanics

The first class will start by providing some background on the themes we will 
be covering. For the lecture, I will try to place the capital market into
long-run perspective and discuss speculative movements. I will also take
some time to review the formative and summative assessments in this course.

**General readings**

+ [@kindlebergerManiasPanicsCrashes1996] Chapter 2 on the anatomy of financial crises^[Kindleberger is a prolific and influential economic historian. He is most famous for this account of bubbles, as well as his interpretation of the global great depression of the interwar period.] [link](https://ebookcentral.proquest.com/lib/kcl/reader.action?docID=5180973&ppg=47)
+ [@cassisCapitalsCapitalHistory2006] chapter 3 [link](https://ebookcentral.proquest.com/lib/kcl/reader.action?docID=802981&ppg=90)
+ [@mollanCityLondonInternational2012] [link](https://www.cambridge.org/core/services/aop-cambridge-core/content/view/9949AB1236E658813B89877F9B0E85AA/S1467222700010867a.pdf/city_of_london_as_an_international_commercial_and_financial_center_since_1900.pdf)

## 2. Lending money abroad: the global sovereign debt crisis of 1825

**General Readings**

+ [@pettisVolatilityMachineEmerging2001] [link]() Chapter 4
+ [@nealFinancialCrisis18251998] [link](https://research.stlouisfed.org/publications/review/1998/05/01/the-financial-crisis-of-1825-and-the-restructuring-of-the-british-financial-system/)
+ [@jenksMigrationBritishCapital1927] [link](https://research.stlouisfed.org/publications/review/1998/05/01/the-financial-crisis-of-1825-and-the-restructuring-of-the-british-financial-system/) Chapter 2.^[Jenk's book is an interesting financial history up to 1875 written in the 1920's before the Great Depression.]
+ [@clavel_2020] [link](https://doi.org/10.1017/eso.2020.25)^[This is a recent reinterpretation of the Poyais scheme.]

**Primary Sources**

+ [@tookeHistoryPricesVol1838] [link](http://archive.org/details/in.ernet.dli.2015.42727) read pp. 148 to 171.
+ [@disraeliInquiryPlansProgress1825] [link](http://hdl.handle.net/2027/mdp.39015063950995) read up to page 21 and then skim a section on one country of your choice.^[Disraeli was involved in speculation in South America with an investor named J. D. Powles who also commissioned him to write this promotional pamphlet.]

## 3. The growth and development of the London Stock Exchange in the 19th century

**General readings**

+ [@taylorOutsideLondonStock2020]
+ [@nealEvolutionStructurePerformance2006]

**Primary sources**

+ Mortimer, Rules and regulations
+ [@RulesRegulationsAdopted1812] [link](https://archive.org/details/rulesregulations00stocuoft)
+ [@RegulationsAdoptedCommittee1847] [link](https://books.googleusercontent.com/books/content?req=AKW5QacIwGHn20rqReIgbN_oGOc_Bt_fW8pdyKxlC09bYAwX3XOssxwTJthFknFUu177BshL5JA8J1ucpjgn-uh2dXpeFeh-fqGdtWZ5D2ixh8Chcrd2wMpyEvEu_l-q5MOwUlpf6GpNjNTpNqwchxfjJ5obkjQCB7thIA9SKnNwpipN0vbYcNRrLG2SClz9MGFKNqf6Z-mqLcRgmOqsko4l53FEfrySnoAnBje8jRT1IqCHzSPXo3juEpnzfEoqiD48Im02BSBkdFqLIDlDiYoXmyDe_RHbOK8c2nBL7rSykitTvXA6mvk)

## 4. The 'classic' Gold Standard


**General readings**

+ [@eichengreenGlobalizingCapitalHistory2008] Chapter on the Classical Gold Standard
+ [@redishEvolutionGoldStandard1990] [link](https://doi.org/10.1017/S0022050700037827)
+ [@bordoGoldStandardTraditional1984] [link](https://core.ac.uk/download/pdf/6900088.pdf)

**Primary sources**

+ [@humeEssaysMoralPolitical1985] Chapter "Of the balance of trade" [link](https://ebookcentral.proquest.com/lib/kcl/reader.action?docID=3327325&ppg=361)
+ [@goschenTheoryForeignExchanges1916] Chapter VI [link](https://hdl.handle.net/2027/uc2.ark:/13960/t9k35zr8s)

## 5. The railway mania of 1845 and crisis of 1847

**General readings**

+ [@campbellGovernmentPolicyBritish2014]
+ [@odlyzkoCollapseRailwayMania2011]

**Primary sources**

+ [@aytounHowWeGot1845] [link](http://www.dtc.umn.edu/~odlyzko/rrsources/glen6.pdf)^[The text is reproduced on Andrew Odlyzko's website. He has supplied a helpful introduction which you should also read.]
+ [@anon.ShortSureGuide1847] [link](https://link.gale.com/apps/doc/U0106715654/MOME?u=ull_ttda&sid=MOME&xid=f232123e)

# Reading Week

## 6. Dissertation Chat 1

## 7. The development of the joint-stock corporation

**General readings**

+ [@taylorCreatingCapitalismJointstock2006]

**Primary sources**

+ Parliamentary enquiries
+ Spencer maybe on railway morals?
+ Share prices!

## 8. The London money market and the crisis of 1866

**General readings**

+ Flandreau, Bignon, Ugolini
+ Acomminotti and Ugolini new paper on acceptances

**Primary sources**

+ Can I get discount window sources?
+ Bagehot

## 9. The Baring Crisis

**General readings**

+ [@floresInformationAsymmetriesConflict2011] [link](https://www.cambridge.org/core/article/information-asymmetries-and-conflict-of-interest-during-the-baring-crisis-188018901/F7A751A4AC3D90669DFD370A387D3E9C)
+ [@dellapaoleraMonetaryFinancialWreck2001] [link](https://www.nber.org/chapters/c8837.pdf)


**Primary sources**

We will be looking at the Barings Archive for sources on the
Argentine crisis of 1890. In addition to the below, you will go
to the [online holdings of the Barings Archive](https://baring.access.preservica.com/archive/) and select
2 documents of your choice. This will likely involve a lot of
searching. There is correspondance in French (Barings to Argentine
Government), Spanish (Argentine Government to Barings), and 
German (consortium banks to Barings) in addition to English 
so feel free to make use of any special language skills if you
like.

+ [@CorrespondenceDiscontoGesellschaft] [link](https://baring.access.preservica.com/uncategorized/IO_b436c123-97cd-42f2-a3c7-aed0cdbbffec/?view=gallery)
+ [@SchemeConversionArgentine1888] [link](https://baring.access.preservica.com/uncategorized/IO_baeb649b-dbe3-46c5-9d0c-afb75887c7a2/)
+ [@ProposalArgentineGovernment] [link](https://baring.access.preservica.com/uncategorized/IO_fabf01ef-16ac-4d52-80f6-8ed5a8add171/?view=gallery)
+ [@CorrespondenceGeorgeWhite] [link](https://baring.access.preservica.com/uncategorized/SO_4177cba6-61a1-46a7-8c10-148bf2e2d464/)
+ [@TelegramDiscontoGesellschaft1889] [link](https://baring.access.preservica.com/uncategorized/SO_77f5601d-3087-4905-8c42-194218d3cbc2/)
+ [@DraftResponseLuis1893] [link](https://baring.access.preservica.com/uncategorized/IO_dd0844b9-214a-4f86-9cd3-ffaf91ed6e25/?view=gallery)
+ [@CorrespondanceFosterBraithwaite] [link](https://baring.access.preservica.com/uncategorized/IO_7627b2eb-bbbc-44db-9eb2-1713862658af/?view=gallery)

## 10. Financial information in the 19th century

**General readings**

+ Grieser maybe? Me and Marc, Lucy Newton's paper, Badmouthing papers, Financial times paper?
+ Make them read a version of the railway mania newspaper war paper I am working on? This might be a nice exercise 

**Primary sources**

+ [@duguidHowReadMoney1902] [link](https://ia802705.us.archive.org/4/items/howtoreadmoneyar00dugurich/howtoreadmoneyar00dugurich.pdf)^[This is a book on how to read financial coverage in 19th century newspapers written at the turn of the century. It's a useful guide to reading some of the other primary sources in the course.]
+ Push the kids into the Financial Times archive and others and make them find coverage they doubt to be objective

# Semester 2

## 11. Dissertation chat 2

## 12. International Finance and WWI

**General readings**

+ [@toozeWorldEconomyGreat2014]

**Primary sources**

+ Chance to read Hobson and maybe Norman Angell

## 13. The reparations problem

**General readings**

+ [@eichengreenGlobalizingCapitalHistory2008]
+ [@eichengreenHowGlobalCurrencies2018]

**Primary sources**

+ Keynes, Mantoux
+ Cunliffe report

## 14. The collapse of the gold standard

**General readings**

+ [@accominottiMotherAllSudden2016] [link](https://doi.org/10.1111/ehr.12128)

**Primary sources**

+ Norman Montagu's diaries from BoE archive?

## 15. Decolonization and the pound

**General readings**

+ Read maybe Balachandran
+ [@ogleFunkMoneyEnd2020]
+ Maylis (if her article is ready) and Schenk
+ [@cainBritishImperialismInnovation1993]

**Primary sources**

+ Not sure yet

# Reading Week

## 16. The Bank of England and the lifeboat operation

**General readings**

+ Not sure yet

**Primary sources**

+ [@bankofenglandSecondaryBankingCrisis1978]
+ [@OralHistoriesCentre] [link](https://www.centreforfinancialhistory.org/oral-histories/)

## 17. Rise of the eurodollar market

**General readings**

+ Maybe Schenk?
+ Also Eichengreen book
+ [@greenAngloAmericanDevelopmentEuromarkets2016]
+ [@helleinerStatesReemergenceGlobal1994]

**Primary sources**

+ [@burkWitnessSeminarOrigins1992]

## 18. The Big Bang and financial deregulation

**General readings**

+ [@attardMakingMarketJobbers2000] [link](https://www.cambridge.org/core/services/aop-cambridge-core/content/view/27B5A3F3C440C45D2B633E603C80C185/S0968565000000019a.pdf/making_a_market_the_jobbers_of_the_london_stock_exchange_18001986.pdf)
+ [@thompsonPyrrhicVictoryGentlemanly2020]
+ [@bellringerBigBangCity2014]
+ [@wadeFinancialRegimeChange2008]

**Primary sources**

+ [@attardLondonStockExchange] [link](https://sas-space.sas.ac.uk/view/collections/lseoh.html) Pick two interviews and listen to them or read transcript
+ Document on FSA regulations from Tooze Chapter 3

## 19. The Great Recession: transatlantic flows and mortgage mania

**General readings**

+ [@toozeCrashedHowDecade2018] ch. 2 and 3
+ Boom and Bust chapter?

**Primary sources**

+ Not totally sure yet
+ Property Ladder season 6
+ [@mckayBigShort2015]
+ Brookings Hamilton project vs IMF or BIS report?

## 20. The Great Recession: The run on repo and the aftermath

**General readings**

+ [@gortonSlappedFaceInvisible2009] [link](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=1401882)
+ [@toozeCrashedHowDecade2018] on international credit lines

**Primary sources**

+ Congressional testimony on CSPAN
+ Parliamentary inquiry on banking stability
+ Andy Haldane speach?

## 21. Review week: Exam Prep